PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS raw_prices(ticker TEXT,date TEXT,open REAL,high REAL,low REAL,close REAL,volume REAL,source TEXT,ingested_at TEXT,PRIMARY KEY(ticker,date,source));
CREATE TABLE IF NOT EXISTS cleaned_prices(ticker TEXT,date TEXT,open REAL,high REAL,low REAL,close REAL,volume REAL,data_confidence REAL,quality_json TEXT,PRIMARY KEY(ticker,date));
CREATE TABLE IF NOT EXISTS feature_definitions(name TEXT PRIMARY KEY,category TEXT,description TEXT,provenance TEXT,version_hash TEXT,created_at TEXT);
CREATE TABLE IF NOT EXISTS features(ticker TEXT,date TEXT,feature_version TEXT,values_json TEXT,computed_at TEXT,source_refs TEXT,PRIMARY KEY(ticker,date,feature_version));
CREATE TABLE IF NOT EXISTS predictions(ticker TEXT,date TEXT,model_id TEXT,probability REAL,expected_return REAL,expected_drawdown REAL,target_before_stop REAL,uncertainty REAL,explanation_json TEXT,PRIMARY KEY(ticker,date,model_id));
CREATE TABLE IF NOT EXISTS montecarlo_metrics(ticker TEXT,date TEXT,engine_weights_json TEXT,metrics_json TEXT,distribution_json TEXT,PRIMARY KEY(ticker,date));
CREATE TABLE IF NOT EXISTS rankings(ticker TEXT,date TEXT,score REAL,action TEXT,position_size REAL,regime TEXT,stress_penalty REAL,confidence REAL,details_json TEXT,PRIMARY KEY(ticker,date));
CREATE TABLE IF NOT EXISTS allocations(ticker TEXT,date TEXT,weight REAL,sector TEXT,risk_budget REAL,reason TEXT,PRIMARY KEY(ticker,date));
CREATE TABLE IF NOT EXISTS trade_plans(ticker TEXT,date TEXT,entry REAL,stop REAL,target REAL,shares REAL,action TEXT,transaction_cost REAL,PRIMARY KEY(ticker,date));
CREATE TABLE IF NOT EXISTS regimes(date TEXT PRIMARY KEY,regime TEXT,confidence REAL,flip_bearish_5d REAL,vol_spike_5d REAL,details_json TEXT);
CREATE TABLE IF NOT EXISTS paper_trades(id INTEGER PRIMARY KEY AUTOINCREMENT,ticker TEXT,opened_date TEXT,closed_date TEXT,side TEXT,shares REAL,entry REAL,exit REAL,pnl REAL,reason TEXT,status TEXT);
CREATE TABLE IF NOT EXISTS positions(ticker TEXT PRIMARY KEY,date TEXT,shares REAL,entry REAL,last_price REAL,pnl REAL,stop REAL,take_profit REAL,weight REAL);
CREATE TABLE IF NOT EXISTS equity_curve(date TEXT PRIMARY KEY,equity REAL,cash REAL,exposure REAL,daily_pnl REAL,drawdown REAL);
CREATE TABLE IF NOT EXISTS models(model_id TEXT PRIMARY KEY,kind TEXT,status TEXT,trained_at TEXT,metrics_json TEXT,path TEXT,feature_version TEXT);
CREATE TABLE IF NOT EXISTS calibration_metrics(date TEXT,model_id TEXT,brier REAL,logloss REAL,curve_json TEXT,PRIMARY KEY(date,model_id));
CREATE TABLE IF NOT EXISTS drift_metrics(date TEXT,model_id TEXT,psi REAL,ks REAL,flag TEXT,details_json TEXT,PRIMARY KEY(date,model_id));
CREATE TABLE IF NOT EXISTS experiments(experiment_id TEXT PRIMARY KEY,name TEXT,status TEXT,started_at TEXT,ended_at TEXT,params_json TEXT,metrics_json TEXT);
CREATE TABLE IF NOT EXISTS champion_challenger(date TEXT,champion_id TEXT,challenger_id TEXT,decision TEXT,reason TEXT,PRIMARY KEY(date,challenger_id));
CREATE TABLE IF NOT EXISTS agent_outputs(date TEXT,agent TEXT,payload_json TEXT,PRIMARY KEY(date,agent));
CREATE TABLE IF NOT EXISTS debate_rounds(date TEXT,round_no INTEGER,agent TEXT,stance TEXT,content TEXT,score REAL,PRIMARY KEY(date,round_no,agent));
CREATE TABLE IF NOT EXISTS agents_transcripts(date TEXT PRIMARY KEY,transcript_json TEXT,verdict_json TEXT);
CREATE TABLE IF NOT EXISTS stress_outputs(ticker TEXT,date TEXT,scenario TEXT,pnl_pct REAL,penalty REAL,details_json TEXT,PRIMARY KEY(ticker,date,scenario));
CREATE TABLE IF NOT EXISTS scenarios(date TEXT,scenario TEXT,details_json TEXT,PRIMARY KEY(date,scenario));
CREATE TABLE IF NOT EXISTS journal_logs(id INTEGER PRIMARY KEY AUTOINCREMENT,ts TEXT,kind TEXT,message TEXT,details_json TEXT);
CREATE TABLE IF NOT EXISTS portfolio_analytics(date TEXT PRIMARY KEY,metrics_json TEXT,factor_json TEXT,alpha_beta_json TEXT,cost_json TEXT,cluster_json TEXT,ruin_json TEXT);
CREATE TABLE IF NOT EXISTS event_risk_flags(ticker TEXT,date TEXT,flag TEXT,severity REAL,details_json TEXT,PRIMARY KEY(ticker,date,flag));
CREATE TABLE IF NOT EXISTS feature_stability(date TEXT,feature TEXT,psi REAL,stable INTEGER,details_json TEXT,PRIMARY KEY(date,feature));
CREATE TABLE IF NOT EXISTS leakage_detection(date TEXT PRIMARY KEY,passed INTEGER,findings_json TEXT);
CREATE TABLE IF NOT EXISTS probability_checks(date TEXT,ticker TEXT,passed INTEGER,findings_json TEXT,PRIMARY KEY(date,ticker));
CREATE TABLE IF NOT EXISTS kill_switch_history(date TEXT PRIMARY KEY,active INTEGER,reason TEXT,metrics_json TEXT);
CREATE TABLE IF NOT EXISTS research_lab(date TEXT,experiment_id TEXT,signal_name TEXT,metrics_json TEXT,accepted INTEGER,PRIMARY KEY(date,experiment_id));
CREATE TABLE IF NOT EXISTS signal_discovery(date TEXT,signal_name TEXT,formula TEXT,score REAL,details_json TEXT,PRIMARY KEY(date,signal_name));
CREATE TABLE IF NOT EXISTS reproducibility_manifests(run_id TEXT PRIMARY KEY,date TEXT,manifest_json TEXT,created_at TEXT);
CREATE TABLE IF NOT EXISTS model_risk_decisions(date TEXT PRIMARY KEY,decision TEXT,reason TEXT,details_json TEXT);
CREATE TABLE IF NOT EXISTS pipeline_runs(run_id TEXT PRIMARY KEY,date TEXT,status TEXT,started_at TEXT,finished_at TEXT,stage_timings_json TEXT,errors_json TEXT);
CREATE TABLE IF NOT EXISTS labels(ticker TEXT,asof_date TEXT,horizon_days INTEGER,realized_return REAL,positive INTEGER,max_drawdown REAL,target_before_stop INTEGER,created_at TEXT,PRIMARY KEY(ticker,asof_date,horizon_days));
CREATE TABLE IF NOT EXISTS analog_memory(ticker TEXT,date TEXT,feature_vector_json TEXT,outcome_json TEXT,PRIMARY KEY(ticker,date));
CREATE TABLE IF NOT EXISTS training_runs(run_id TEXT PRIMARY KEY,started_at TEXT,finished_at TEXT,rows_used INTEGER,cv_metrics_json TEXT,model_id TEXT,status TEXT);
CREATE TABLE IF NOT EXISTS universe_health(date TEXT PRIMARY KEY,requested INTEGER,loaded INTEGER,deep_analyzed INTEGER,failed INTEGER,source TEXT,failover_mode TEXT,details_json TEXT);
CREATE TABLE IF NOT EXISTS mc_engine_validation(ticker TEXT,asof_date TEXT,engine TEXT,predicted_probability REAL,outcome INTEGER,brier REAL,PRIMARY KEY(ticker,asof_date,engine));
CREATE TABLE IF NOT EXISTS broker_orders(client_order_id TEXT PRIMARY KEY,broker_order_id TEXT,ticker TEXT,date TEXT,status TEXT,payload_json TEXT,response_json TEXT,updated_at TEXT);
CREATE TABLE IF NOT EXISTS broker_account_snapshots(date TEXT PRIMARY KEY,equity REAL,cash REAL,buying_power REAL,details_json TEXT);
